var_list = [1, 'строка', True, False, [1, 2, 3]]
print(var_list[0])
print(type(var_list[0]))
print(var_list[1])
print(type(var_list[1]))
print(var_list[2])
print(type(var_list[2]))
print(var_list[3])
print(type(var_list[3]))
print(var_list[4])
print(type(var_list[4]))
